### ISSUE TITLE
Remove underline from TBS logo

### ISSUE THREAD

**Issue by cpshaw99** [CRJI/theblacksea.eu#88]
Links are underlined when mouse hovers over them. Needs removing

**Comment by nightsh** [comment]
Only issue I have with this (it came up in the old site as well) - due to the website's pale color scheme, it might be difficult to notice the color change on hovering. For example, if your display is crappy enough, you might not see a two-letter link that is light gray as opposed to darker gray text. Also on hover, light blue vs gray-ish. Think about it.

However, this is a very easy change. Just let me know here if you're positive the underlines should be removed :slightly_smiling_face:

**Comment by cpshaw99** [comment]
We can leave i on the story links, but how about taking it off "The Black Sea" in the Nav bar?
